# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-10-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_auto_20241022_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfossaccess',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donate.FossSubscription'),
        ),
    ]
