# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-10-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_auto_20241022_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfossaccess',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
    ]
