# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-10-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_auto_20241025_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfossaccess',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
